### ISSUE TITLE
Query regarding Level-7

### ISSUE THREAD

**Issue by radeon2525** [nus-cs2103-AY2324S2/forum#116]
I have been able to create a new file called logfile.txt however it is not getting saved and I am getting the following error:

Exception in thread "main" java.io.FileNotFoundException: .\data\logfile.txt (The system cannot find the path specified)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at java.base/java.io.FileReader.<init>(FileReader.java:75)
	at FileIO.readFromFile(FileIO.java:27)
	at Duke.<init>(Duke.java:12)
	at Duke.main(Duke.java:23)

Process finished with exit code 1

Could someone help me point out where could I be having an error.

**Comment by miffi** [comment]
> Exception in thread "main" java.io.FileNotFoundException: .\data\logfile.txt (The system cannot find the path specified)
> >  (The system cannot find the path specified)

you have to create the directory as well I'm guessing

**Comment by radeon2525** [comment]
Alright the error seems to be resolved. Thank you
