### ISSUE TITLE
Unable to run addressbook.jar when setting up AB3

### ISSUE THREAD

**Issue by Anant1902** [nus-cs2103-AY2324S2/forum#142]
After downloading addressbook.jar from the link here (https://se-education.org/addressbook-level3/UserGuide.html), I have tried running the command 'java -jar path-to/addressbook.jar' multiple times, however, the error shown below keeps popping up. I have triple-checked that I am running java SDK 11 and all my commands and paths are correct.

Does anyone have any suggestions? Mac user here by the way!

```
/Library/Java/JavaVirtualMachines/jdk-11.jdk/Contents/Home/bin/java -Dfile.encoding=UTF-8 -jar /Users/anant/Documents/Anant/nus/Year 2 Semester 2/CS2103T/IP-NEW/addressbook.jar
Jan 31, 2024 4:45:06 PM seedu.address.Main main
WARNING: The warning about Unsupported JavaFX configuration below can be ignored.
Jan 31, 2024 4:45:06 PM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @17055742'
Loading library prism_es2 from resource failed: java.lang.UnsatisfiedLinkError: Can't load library: /Users/anant/.openjfx/cache/17.0.7/libprism_es2.dylib
java.lang.UnsatisfiedLinkError: Can't load library: /Users/anant/.openjfx/cache/17.0.7/libprism_es2.dylib
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2622)
	at java.base/java.lang.Runtime.load0(Runtime.java:765)
	at java.base/java.lang.System.load(System.java:1852)
	at com.sun.glass.utils.NativeLibLoader.installLibraryFromResource(NativeLibLoader.java:217)
	at com.sun.glass.utils.NativeLibLoader.loadLibraryFromResource(NativeLibLoader.java:197)
	at com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:138)
	at com.sun.glass.utils.NativeLibLoader.loadLibrary(NativeLibLoader.java:54)
	at com.sun.prism.es2.ES2Pipeline.lambda$static$0(ES2Pipeline.java:63)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.prism.es2.ES2Pipeline.<clinit>(ES2Pipeline.java:52)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at com.sun.prism.GraphicsPipeline.createPipeline(GraphicsPipeline.java:218)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:92)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
	at java.base/java.lang.Thread.run(Thread.java:834)
Loading library prism_sw from resource failed: java.lang.UnsatisfiedLinkError: Can't load library: /Users/anant/.openjfx/cache/17.0.7/libprism_sw.dylib
java.lang.UnsatisfiedLinkError: Can't load library: /Users/anant/.openjfx/cache/17.0.7/libprism_sw.dylib
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2622)
	at java.base/java.lang.Runtime.load0(Runtime.java:765)
	at java.base/java.lang.System.load(System.java:1852)
	at com.sun.glass.utils.NativeLibLoader.installLibraryFromResource(NativeLibLoader.java:217)
	at com.sun.glass.utils.NativeLibLoader.loadLibraryFromResource(NativeLibLoader.java:197)
	at com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:138)
	at com.sun.glass.utils.NativeLibLoader.loadLibrary(NativeLibLoader.java:54)
	at com.sun.prism.sw.SWPipeline.lambda$static$0(SWPipeline.java:43)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.prism.sw.SWPipeline.<clinit>(SWPipeline.java:42)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at com.sun.prism.GraphicsPipeline.createPipeline(GraphicsPipeline.java:218)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:92)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
	at java.base/java.lang.Thread.run(Thread.java:834)
Graphics Device initialization failed for :  es2, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:283)
	at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:254)
	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:266)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:291)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:163)
	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:659)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:679)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:95)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
	... 1 more
Exception in thread "main" java.lang.RuntimeException: No toolkit found
	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:278)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:291)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:163)
	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:659)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:679)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
	at java.base/java.lang.Thread.run(Thread.java:834)

Process finished with exit code 1
```

**Comment by Jerome-j** [comment]
Hello, 

1. can you try to run the `java --version` command and paste the output here:
2. are you using a Apple Silicon Mac?

I suspect it was the same issue as #119

**Comment by Anant1902** [comment]
> Hello,
> 
> 1. can you try to run the `java --version` command and paste the output here:
> 2. are you using a Apple Silicon Mac?
> 
> I suspect it was the same issue as #119

Hi Jerome, thanks for the prompt reply. I have a M2 chip, so i think Silicon yes. This is what running java --version shows:

```
(base) MacBook-Air-51:~ anant$ java --version
java 11.0.22 2024-01-16 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.22+9-LTS-219)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.22+9-LTS-219, mixed mode)
```

**Comment by Jerome-j** [comment]
Hi Anant, no worries. I suspect your Java 11 is a different edition (build?/branch?/vendor?)

I installed the one that I mentioned in #119, and my output is different

```
openjdk 11.0.12 2021-07-20 LTS
OpenJDK Runtime Environment Zulu11.50+19-CA (build 11.0.12+7-LTS)
OpenJDK 64-Bit Server VM Zulu11.50+19-CA (build 11.0.12+7-LTS, mixed mode)
```

You can simply download from https://www.azul.com/downloads/?version=java-11-lts&os=macos&architecture=arm-64-bit&package=jdk-fx#downloads-table-zulu. 

Make sure you check on this box to see old versions.
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/49815108/4512edb5-ca44-4ef0-a804-21c996b2c369)

Prof wrote a guide here: https://nus-cs2103-ay2324s2.github.io/website/admin/programmingLanguages.html#programming-language under the "[IMPORTANT] Advisory for  Mac users" - please take a look

**Comment by Anant1902** [comment]
> Hi Anant, no worries. I suspect your Java 11 is a different edition (build?/branch?/vendor?)
> 
> I installed the one that I mentioned in #119, and my output is different
> 
> ```
> openjdk 11.0.12 2021-07-20 LTS
> OpenJDK Runtime Environment Zulu11.50+19-CA (build 11.0.12+7-LTS)
> OpenJDK 64-Bit Server VM Zulu11.50+19-CA (build 11.0.12+7-LTS, mixed mode)
> ```
> 
> You can simply download from https://www.azul.com/downloads/?version=java-11-lts&os=macos&architecture=arm-64-bit&package=jdk-fx#downloads-table-zulu.
> 
> Make sure you check on this box to see old versions. ![image](https://private-user-images.githubusercontent.com/49815108/301103134-4512edb5-ca44-4ef0-a804-21c996b2c369.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2OTI1ODAsIm5iZiI6MTcwNjY5MjI4MCwicGF0aCI6Ii80OTgxNTEwOC8zMDExMDMxMzQtNDUxMmVkYjUtY2E0NC00ZWYwLWE4MDQtMjFjOTk2YjJjMzY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDA5MTEyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjY2ZhZjA5YzAzMWFkNjU1YzczM2RhZDMyMjczYzI4ZGJjZjgyNDA4N2I5NmI3ODkzNWI4ZDAyYTllMGVmODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gG92Up2zJucjtiotH5njmkUekZTJV-VdgnHBlf6-3-M)
> 
> Prof wrote a guide here: https://nus-cs2103-ay2324s2.github.io/website/admin/programmingLanguages.html#programming-language under the "[IMPORTANT] Advisory for Mac users" - please take a look

Yes! I was just going to reply by saying that the solution you brought up in the previous issue (that you linked) worked perfectly. But either way, thanks for your help! Closing this issue :)
