### ISSUE TITLE
Javajx fmxl load exception

### ISSUE THREAD

**Issue by hjuntan** [nus-cs2103-AY2324S2/forum#251]
I encounter an error when I'm running the Main.java:

```
Feb 11, 2024 3:24:19 PM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @64eaa5b5'
javafx.fxml.LoadException: 
/C:/Users/User/Desktop/Lecture%20notes/Y2S2/CS2103T/repos/ip/build/resources/main/view/MainWindow.fxml:9

	at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2714)
	at javafx.fxml.FXMLLoader$ValueElement.processAttribute(FXMLLoader.java:944)
	at javafx.fxml.FXMLLoader$InstanceDeclarationElement.processAttribute(FXMLLoader.java:981)
	at javafx.fxml.FXMLLoader$Element.processStartElement(FXMLLoader.java:230)
	at javafx.fxml.FXMLLoader$ValueElement.processStartElement(FXMLLoader.java:755)
Unsupported JavaFX configuration: classes were loaded from 'unnamed module @64eaa5b5'

	at javafx.fxml.FXMLLoader.processStartElement(FXMLLoader.java:2845)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2641)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2555)
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2523)
	at toothless.Main.start(Main.java:22)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:847)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:484)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:457)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:456)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at javafx.fxml.FXMLLoader$ValueElement.processAttribute(FXMLLoader.java:939)
Caused by: java.lang.reflect.InvocationTargetException

	... 17 more
Caused by: java.lang.NullPointerException: Input stream must not be null
	at javafx.scene.image.Image.validateInputStream(Image.java:1137)
	at javafx.scene.image.Image.<init>(Image.java:704)
	at toothless.MainWindow.<init>(MainWindow.java:26)
	... 22 more
Caused by: java.lang.NullPointerException: Input stream must not be null
```
I'm not sure what's the error as it is able to find the MainWindow.fxml file followed in the Javafx tutorial.

**Comment by gerteck** [comment]
Is your `MainWindow.java` included in a package? I encountered a similar error, where I had to reconfigure the fxml file to point to `<package>.MainWindow`.

**Comment by HongRay** [comment]
May I know what did you changed in your files that caused the error?

**Comment by jjchee77** [comment]
Happy lunar new year.

Based on the stacktrace you provided, I believe the error is caused by the null value being passed to instantiate a `javafx.scene.image.Image` object that is used in your fxml file. This is likely due to the image not being found on your file system.

If you are following the tutorial from the website, the issue is likely caused by missing profile picture(s) of your toothless chatbot and the user which causes the `getResourceAsStream` method to [return null](https://docs.oracle.com/en%2Fjava%2Fjavase%2F11%2Fdocs%2Fapi%2F%2F/java.base/java/lang/ClassLoader.html#getResourceAsStream(java.lang.String)) as your specified resource(s) are not found.

  `private final Image userImage = new Image(this.getClass().getResourceAsStream("/images/DaUser.png"));`
`private final Image dukeImage = new Image(this.getClass().getResourceAsStream("/images/DaDuke.png"));`

If that is indeed the issue, you may wish to follow my directory structure (referenced from the cs2103t website) which can be found [here ](https://github.com/jjchee77/ip/tree/master/src/main/resources)

It is difficult to pinpoint the exact issue without being able to see your code, but hope this helps.

**Comment by hjuntan** [comment]
Happy lunar new year to you as well. 🎆 

I've found the error. Turns out I've renamed my files and have not update the appropriate file names.
