### ISSUE TITLE
Smoke test help

### ISSUE THREAD

**Issue by reetmitra** [nus-cs2103-AY2324S2/forum#458]
On Linux, using Java 11, for the EchoPilot.jar uploaded on 02-28-2024 (MM-DD-YYYY) at 15:39:21:
Graphics Device initialization failed for : es2, sw Error initializing QuantumRenderer: no suitable pipeline found java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found at

This is the issue my smoke test is having, could anyone help me out with how to resolve this?

**Comment by damithc** [comment]
@reetmitra Which OS and which JDK did you use to build this JAR file?

Other Linux users, can confirm you also get the same error for this JAR?

**Comment by francisyzy** [comment]
Hello, senior from a previous batch here, testing on Kali.

Yes I face the same issue: `Graphics Device initialization failed for : es2, sw Error initializing QuantumRenderer: no suitable pipeline found`

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/24467184/936f0d1d-13e4-48f1-b229-d7d58e7418a2)

Saw that you compiled on Mac and I've tried both Java 11 and 17 with errors as well:
<details>

```log
francisyzy@Pro14 Downloads % java --version
openjdk 11.0.21 2023-10-17 LTS
OpenJDK Runtime Environment Microsoft-8519785 (build 11.0.21+9-LTS)
OpenJDK 64-Bit Server VM Microsoft-8519785 (build 11.0.21+9-LTS, mixed mode)
francisyzy@Pro14 Downloads % java -jar EchoPilot.jar                                  
Loading library prism_es2 from resource failed: java.lang.UnsatisfiedLinkError: Can't load library: /Users/francisyzy/.openjfx/cache/11/libprism_es2.dylib
java.lang.UnsatisfiedLinkError: Can't load library: /Users/francisyzy/.openjfx/cache/11/libprism_es2.dylib
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2638)
	at java.base/java.lang.Runtime.load0(Runtime.java:768)
	at java.base/java.lang.System.load(System.java:1850)
	at com.sun.glass.utils.NativeLibLoader.installLibraryFromResource(NativeLibLoader.java:205)
	at com.sun.glass.utils.NativeLibLoader.loadLibraryFromResource(NativeLibLoader.java:185)
	at com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:157)
	at com.sun.glass.utils.NativeLibLoader.loadLibrary(NativeLibLoader.java:52)
	at com.sun.prism.es2.ES2Pipeline.lambda$static$0(ES2Pipeline.java:68)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.prism.es2.ES2Pipeline.<clinit>(ES2Pipeline.java:50)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at com.sun.prism.GraphicsPipeline.createPipeline(GraphicsPipeline.java:187)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:91)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
	at java.base/java.lang.Thread.run(Thread.java:829)
Loading library prism_sw from resource failed: java.lang.UnsatisfiedLinkError: Can't load library: /Users/francisyzy/.openjfx/cache/11/libprism_sw.dylib
java.lang.UnsatisfiedLinkError: Can't load library: /Users/francisyzy/.openjfx/cache/11/libprism_sw.dylib
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2638)
	at java.base/java.lang.Runtime.load0(Runtime.java:768)
	at java.base/java.lang.System.load(System.java:1850)
	at com.sun.glass.utils.NativeLibLoader.installLibraryFromResource(NativeLibLoader.java:205)
	at com.sun.glass.utils.NativeLibLoader.loadLibraryFromResource(NativeLibLoader.java:185)
	at com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:157)
	at com.sun.glass.utils.NativeLibLoader.loadLibrary(NativeLibLoader.java:52)
	at com.sun.prism.sw.SWPipeline.lambda$static$0(SWPipeline.java:42)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.prism.sw.SWPipeline.<clinit>(SWPipeline.java:41)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at com.sun.prism.GraphicsPipeline.createPipeline(GraphicsPipeline.java:187)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:91)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
	at java.base/java.lang.Thread.run(Thread.java:829)
Graphics Device initialization failed for :  es2, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:280)
	at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:222)
	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:260)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:94)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
	... 1 more
Exception in thread "main" java.lang.RuntimeException: No toolkit found
	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:272)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

```log
francisyzy@Pro14 Downloads % java --version             
openjdk 17.0.9 2023-10-17 LTS
OpenJDK Runtime Environment Microsoft-8552009 (build 17.0.9+8-LTS)
OpenJDK 64-Bit Server VM Microsoft-8552009 (build 17.0.9+8-LTS, mixed mode)
francisyzy@Pro14 Downloads % java -jar EchoPilot.jar   
Loading library prism_es2 from resource failed: java.lang.UnsatisfiedLinkError: /Users/francisyzy/.openjfx/cache/11/libprism_es2.dylib: dlopen(/Users/francisyzy/.openjfx/cache/11/libprism_es2.dylib, 0x0001): tried: '/Users/francisyzy/.openjfx/cache/11/libprism_es2.dylib' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))
java.lang.UnsatisfiedLinkError: /Users/francisyzy/.openjfx/cache/11/libprism_es2.dylib: dlopen(/Users/francisyzy/.openjfx/cache/11/libprism_es2.dylib, 0x0001): tried: '/Users/francisyzy/.openjfx/cache/11/libprism_es2.dylib' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2394)
	at java.base/java.lang.Runtime.load0(Runtime.java:755)
	at java.base/java.lang.System.load(System.java:1953)
	at com.sun.glass.utils.NativeLibLoader.installLibraryFromResource(NativeLibLoader.java:205)
	at com.sun.glass.utils.NativeLibLoader.loadLibraryFromResource(NativeLibLoader.java:185)
	at com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:157)
	at com.sun.glass.utils.NativeLibLoader.loadLibrary(NativeLibLoader.java:52)
	at com.sun.prism.es2.ES2Pipeline.lambda$static$0(ES2Pipeline.java:68)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at com.sun.prism.es2.ES2Pipeline.<clinit>(ES2Pipeline.java:50)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:375)
	at com.sun.prism.GraphicsPipeline.createPipeline(GraphicsPipeline.java:187)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:91)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
	at java.base/java.lang.Thread.run(Thread.java:840)
Loading library prism_sw from resource failed: java.lang.UnsatisfiedLinkError: /Users/francisyzy/.openjfx/cache/11/libprism_sw.dylib: dlopen(/Users/francisyzy/.openjfx/cache/11/libprism_sw.dylib, 0x0001): tried: '/Users/francisyzy/.openjfx/cache/11/libprism_sw.dylib' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))
java.lang.UnsatisfiedLinkError: /Users/francisyzy/.openjfx/cache/11/libprism_sw.dylib: dlopen(/Users/francisyzy/.openjfx/cache/11/libprism_sw.dylib, 0x0001): tried: '/Users/francisyzy/.openjfx/cache/11/libprism_sw.dylib' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2394)
	at java.base/java.lang.Runtime.load0(Runtime.java:755)
	at java.base/java.lang.System.load(System.java:1953)
	at com.sun.glass.utils.NativeLibLoader.installLibraryFromResource(NativeLibLoader.java:205)
	at com.sun.glass.utils.NativeLibLoader.loadLibraryFromResource(NativeLibLoader.java:185)
	at com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:157)
	at com.sun.glass.utils.NativeLibLoader.loadLibrary(NativeLibLoader.java:52)
	at com.sun.prism.sw.SWPipeline.lambda$static$0(SWPipeline.java:42)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at com.sun.prism.sw.SWPipeline.<clinit>(SWPipeline.java:41)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:375)
	at com.sun.prism.GraphicsPipeline.createPipeline(GraphicsPipeline.java:187)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:91)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
	at java.base/java.lang.Thread.run(Thread.java:840)
Graphics Device initialization failed for :  es2, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:280)
	at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:222)
	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:260)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:94)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
	... 1 more
Exception in thread "main" java.lang.RuntimeException: No toolkit found
	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:272)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.base/java.lang.Thread.run(Thread.java:840
```

</details>

**Comment by hansstanley** [comment]
Hi @reetmitra, senior from a previous batch here, I experienced the same error on Fedora 39 with Java 11.

I also noticed your JavaFX version being 19.0.2.1 while your peers and the guide use JavaFX 17, I can't ascertain whether that would fix your issue but perhaps you could try downgrading your JavaFX version?

**Comment by damithc** [comment]
@reetmitra Which OS are you on, and how exactly did you create the JAR file?

**Comment by reetmitra** [comment]
> @reetmitra Which OS are you on, and how exactly did you create the JAR file?

MacOS. I created the JAR file using the shadowJar command.

**Comment by reetmitra** [comment]
@hansstanley i'll try changing that, thank you!

**Comment by damithc** [comment]
> MacOS. I created the JAR file using the shadowJar command.

What's your output for the `java -version` command, in the same terminal you ran the `./gradlew clean shadowJar` command?

**Comment by reetmitra** [comment]
> > MacOS. I created the JAR file using the shadowJar command.
> 
> What's your output for the `java -version` command, in the same terminal you ran the `./gradlew clean shadowJar` command?

It shows this at the moment : java version "17.0.9" 2023-10-17 LTS

**Comment by reetmitra** [comment]
I managed to fix this, it now shows : java version "11.0.21" 2023-10-17 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.21+9-LTS-193)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.21+9-LTS-193, mixed mode)

I will try releasing a new JAR file.

**Comment by damithc** [comment]
@reetmitra Make sure you use the exact Azul JDK we have prescribed for Mac users https://nus-cs2103-ay2324s2.github.io/website/admin/programmingLanguages.html

**Comment by reetmitra** [comment]
@damithc I now have this output : openjdk version "11.0.22" 2024-01-16 LTS
OpenJDK Runtime Environment Zulu11.70+15-CA (build 11.0.22+7-LTS)
OpenJDK 64-Bit Server VM Zulu11.70+15-CA (build 11.0.22+7-LTS, mixed mode)

**Comment by reetmitra** [comment]
@damithc I've updated the release once more after running the shadowJar command after ensuring that the exact Azul JDK has to be used.

**Comment by lhy-hoyin** [comment]
@reetmitra Would you be able to provide the link to your latest jar file here?
\- senior from previous batch

**Comment by francisyzy** [comment]
Senior from a previous batch here

Using your latest jar from the [releases](https://github.com/reetmitra/ip/releases) and testing using the java version specified `java 11.0.19.fx-zulu`, your jar file runs on Kali Linux.

<img width="699" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/24467184/243875e8-0f92-4dc5-b790-90b19bb7cab5">

It also runs on Mac as well!

<img width="993" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/24467184/a209d2e6-06f6-400d-94d9-91c8bf2e0a9b">


<details>
However when using other versions of Java (which worked for other students), the jar does not run_. I don’t think this is a huge deal as it could work with the version specified by the course_

<img width="634" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/24467184/a7a56845-490c-4420-bacb-c1021f55221e">

</details>

**Comment by damithc** [comment]
> However when using other versions of Java (which worked for other students), the jar does not run. I don’t think this is a huge deal as it could work with the version specified by the course

On Linux, the JAR should work with any JDK 11 distro. Only Mac users are required to use the Zulu distro.

**Comment by reetmitra** [comment]
@francisyzy thank you for testing it out!
